version: 0.2

phases:
  pre_build:
    commands:
      - echo getting the git hash $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
      - IMAGE_TAG=$(echo $CODEBUILD_SOURCE_VERSION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_URI}:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files: imagedefinitions.json
